#!/bin/bash


dev(){

  clojure -A:core -m tf.main

}

dock() {
    docker build -t tmp.deeplearning.tf .
    docker run --gpus all \
                --rm \
                --name tf \
                -it \
                -p 7788:7788 \
                -v "$(pwd)":/opt/app \
                 tmp.deeplearning.tf \
                 bash
}


"$@"