#!/bin/bash


dev(){

  clojure -A:core -m tf.main

}

dock() {
    docker build -t sample.ml.tf .
    docker run --gpus all \
                --rm \
                --name tf \
                -it \
                -p 7788:7888 \
                -v "$(pwd)":/opt/app \
                 sample.ml.tf \
                 bash
}


"$@"