#!/bin/bash


shadow(){
    ./node_modules/.bin/shadow-cljs "$@"
}

dev(){
    yarn
    shadow -A:core watch app
}

entry(){
    node target/main.js
}

release(){
    yarn
    shadow -A:core release app
}


"$@"
