#!/bin/bash


clean(){
  rm -rf classes .cpcache
}

dev(){

  clojure -A:core:local -O:mem -m gvm.main 

}

native(){

  clojure -A:core:local:native-image

}

gpip(){
   graalpython -m ginstall
}


"$@"