#!/bin/bash


dock() {
    docker build -t test.deeplearning.gvm .
    docker run  --rm \
                --name gvm \
                --memory 16g \
                --cpus 4.000 \
                -it \
                -p 7788:7788 \
                -v "$(pwd)":/opt/app \
                 test.deeplearning.gvm \
                 bash
}

"$@"