#!/bin/bash


dev(){

  lein run dev

}

clean(){

  rm -rf .cpcache classes target

}

dock() {
    sudo xhost +
    docker build -t tmp.deeplearning.lucene .
    docker run  --gpus all \
                --env DISPLAY=${DISPLAY} \
                -v /tmp/.X11-unix:/tmp/.X11-unix \
                --rm \
                --name lucene \
                --memory 12g \
                --cpus 4.000 \
                -it \
                -p 7788:7788 \
                -v "$(pwd)":/opt/app \
                 tmp.deeplearning.lucene \
                 bash
}

"$@"