#!/bin/bash


dev(){

  clojure -A:core -m d2l.main

}

permissions(){
    sudo chmod -R 777 tmp/ 
}


dock() {
    docker build -t test.deeplearning.d2l .
    docker run --gpus all \
                --rm \
                --name d2l \
                -it \
                -p 7788:7788 \
                -v "$(pwd)":/opt/app \
                 test.deeplearning.d2l \
                 bash
}





"$@"