#!/bin/bash


dev(){

  lein run dev

}

clean(){

  rm -rf .cpcache classes target

}

link_checkouts(){
  CHECKOUTS=checkouts
  mkdir -p $CHECKOUTS

  ln -s /opt/code/pad $CHECKOUTS/pad
}

dock() {
    sudo xhost +
    docker build -t sample.ml.dl4j .
    docker run  --gpus all \
                --env DISPLAY=${DISPLAY} \
                -v /tmp/.X11-unix:/tmp/.X11-unix \
                --rm \
                --name dl4j \
                --memory 12g \
                --cpus 4.000 \
                -it \
                -p 7788:7788 \
                -p 9000:9000 \
                -v "$(pwd)":/opt/app \
                -v "$(pwd)"/.deeplearning4j:/root/.deeplearning4j \
                -v "$(pwd)"/dl4j-examples-data:/root/dl4j-examples-data \
                 sample.ml.dl4j \
                 bash
}

"$@"